### ISSUE TITLE
Add static code analyzer and badge

### ISSUE THREAD

**Issue by etimberg** [opusonesolutions/asciigraf#17]
[Code climate](https://codeclimate.com/) is a static analyzer that can be hooked up to PRs, etc. It produces reports like https://codeclimate.com/github/chartjs/Chart.js/issues.

**Comment by AnjoMan** [comment]
I think this is closed by  https://github.com/opusonesolutions/asciigraf/commit/2ec371fd53ad70cedb526a365edd423bb1165f08, thanks to @greatestape
